# Generated by Django 5.2.7 on 2025-10-27 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="Title")),
                (
                    "first_period_start",
                    models.DateField(help_text="Date when the lease starts.", verbose_name="First period start"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", "Russian ruble"), ("USD", "US dollar"), ("EUR", "Euro")],
                        default="RUB",
                        help_text="All rent rates and payments for this lease are in this currency.",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lease",
                "verbose_name_plural": "Leases",
                "ordering": ("-first_period_start", "id"),
            },
        ),
        migrations.CreateModel(
            name="ExtraPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("tenant_to_landlord", "Tenant to landlord"),
                            ("landlord_to_tenant", "Landlord to tenant"),
                        ],
                        max_length=32,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned payment"),
                            ("reserved", "Reserved for landlord"),
                            ("paid", "Paid"),
                            ("canceled", "Canceled"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "agreed_date",
                    models.DateField(
                        help_text="Date when the parties agreed on this payment.", verbose_name="Agreed date"
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, help_text="Actual date of payment (if paid).", null=True, verbose_name="Paid date"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Amount")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_payments",
                        to="leases.lease",
                        verbose_name="Lease",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extra payment",
                "verbose_name_plural": "Extra payments",
                "ordering": ("-agreed_date", "id"),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "date",
                    models.DateField(
                        help_text="Date when the money moved or is expected to move.", verbose_name="Date"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Amount")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned payment"),
                            ("reserved", "Reserved for landlord"),
                            ("paid", "Paid to landlord"),
                        ],
                        default="paid",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "target_period_start",
                    models.DateField(
                        blank=True,
                        help_text="Optional rent period this payment is linked to (start date).",
                        null=True,
                        verbose_name="Target period start",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255, verbose_name="Notes")),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="leases.lease",
                        verbose_name="Lease",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ("-date", "id"),
            },
        ),
        migrations.CreateModel(
            name="MoneyTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "date",
                    models.DateField(
                        help_text="Date when the money moved or is expected to move.", verbose_name="Date"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Amount")),
                ("notes", models.CharField(blank=True, max_length=255, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "extra_payments_covered",
                    models.ManyToManyField(
                        related_name="money_transactions",
                        to="leases.extrapayment",
                        verbose_name="Extra payments covered",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_transactions",
                        to="leases.lease",
                        verbose_name="Lease",
                    ),
                ),
                (
                    "payments_covered",
                    models.ManyToManyField(
                        related_name="money_transactions", to="leases.payment", verbose_name="Payments covered"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Monthly rent amount.", max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when this rent amount starts applying.", verbose_name="Effective from"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when this amount stops applying (exclusive). Leave empty for the current rate.",
                        null=True,
                        verbose_name="Effective until",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255, verbose_name="Notes")),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rent_rates",
                        to="leases.lease",
                        verbose_name="Lease",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rent rate",
                "verbose_name_plural": "Rent rates",
                "ordering": ("effective_date", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="extrapayment",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="extra_payment_amount_gt_0"),
        ),
        migrations.AddConstraint(
            model_name="extrapayment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("paid_date__isnull", True), ("paid_date__gte", models.F("agreed_date")), _connector="OR"
                ),
                name="extra_payment_paid_after_agreed",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentrate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True), ("end_date__gt", models.F("effective_date")), _connector="OR"
                ),
                name="rent_rate_end_after_start",
            ),
        ),
    ]
