# Generated by Django 5.2.9 on 2026-01-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned payment"),
                    ("overdue", "Overdue payment"),
                    ("reserved", "Reserved for landlord"),
                    ("paid", "Paid to landlord"),
                ],
                default="paid",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
